/**
 * Privacy policy page.
 */
export default function PrivacyPage() {
  return (
    <section className="max-w-3xl mx-auto px-4 sm:px-6 py-20">
      <h1 className="text-3xl font-bold text-slate-900 mb-2">Privacy Policy</h1>
      <p className="text-slate-500 text-sm mb-10">Last updated: February 1, 2026</p>

      <div className="prose prose-slate max-w-none text-sm leading-relaxed space-y-8">
        <div>
          <h2 className="text-lg font-semibold text-slate-900 mb-2">1. Information we collect</h2>
          <p className="text-slate-600">
            We collect information you provide directly to us — such as your name, email address,
            and agency information when you register — and information generated by your use of
            OnRampd, such as project activity and engagement data.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-slate-900 mb-2">2. How we use your information</h2>
          <p className="text-slate-600 mb-2">We use the information we collect to:</p>
          <ul className="list-disc pl-5 space-y-1 text-slate-600">
            <li>Provide, maintain, and improve OnRampd</li>
            <li>Process transactions and send related information</li>
            <li>Send technical notices, updates, and security alerts</li>
            <li>Respond to your comments and questions</li>
            <li>Monitor usage patterns to improve user experience</li>
          </ul>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-slate-900 mb-2">3. Data sharing</h2>
          <p className="text-slate-600">
            We do not sell your personal information. We may share information with service
            providers (Supabase for database hosting, Stripe for payment processing, Resend for
            email delivery) who process data on our behalf under strict data processing agreements.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-slate-900 mb-2">4. Data retention</h2>
          <p className="text-slate-600">
            We retain your account and project data for as long as your account is active. Upon
            account deletion, we delete your data within 30 days, except where required by law.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-slate-900 mb-2">5. Security</h2>
          <p className="text-slate-600">
            We use row-level security to ensure your organization&apos;s data is isolated from other
            tenants. All data is encrypted in transit (TLS) and at rest.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-slate-900 mb-2">6. Your rights</h2>
          <p className="text-slate-600">
            You may request access to, correction of, or deletion of your personal data at any
            time by contacting us at privacy@onrampd.com.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-slate-900 mb-2">7. Contact</h2>
          <p className="text-slate-600">
            For privacy-related inquiries, contact us at{' '}
            <a href="mailto:privacy@onrampd.com" className="text-red-700 hover:underline">
              privacy@onrampd.com
            </a>.
          </p>
        </div>
      </div>
    </section>
  )
}
